"""Concise, generated report of the coupled geometry and aerodynamic inputs."""
import json
from .native_design_kernel import ROOT
from .study_open_sizing import validate


def publication():
    m=json.loads((ROOT/'docs/analysis/coupled-mass-reference.json').read_text())
    a=json.loads((ROOT/'docs/analysis/wing-polar-grid.json').read_text())
    validate(m['sourceHashes']);validate(a['driverHashes'])
    r=m['mass'];cases=[c for c in a['cases'] if not c['reverseChord'] and c['camberScale']>0]
    lines=['# Coupled sizing inputs','','<!-- Generated by scripts.publish_coupled_inputs. -->','',
      '**Reference inputs, not the optimized candidate.** The coupled search and sensitivity studies are reported in [coupled results](coupled-results.md). The reference geometry uses the previous two-metre dimensions with recomputed skin/rib mass and centroids. It is not a newly feasible design.','',
      '## Geometry and mass','',f"Calculated mass: **{r['totalMass']:.2f} kg**. Center of gravity: ({r['cgX']:.4f}, {r['cgY']:.4f}, {r['cgZ']:.4f}) m in the hull reference frame. The reference plane is not the solved waterline.",'',
      '| Component | Calculated mass (kg) |','|---|---:|']
    for title,key in [('Hull','hullMass'),('Wing','wingMass'),('Keel structure','keelMass'),('Rudder structure','rudderMass'),('Battery','batteryMass'),('Solar panel','panelMass'),('Wing drive','wingDriveMass'),('Rudder drive','rudderDriveMass'),('Equipment/attachments','equipmentMass')]:lines.append(f'| {title} | {r[key]:.3f} |')
    lines += [f"| Ballast | {m['design']['ballast_kg']:.3f} |",'',
      'External mesh faces supply skin area; closed volumes supply diaphragm-rib allocations. Native SysML accounts for printed substrate, glass, resin, finish, seam tape and equipment. Thin-wall section properties use the actual reference section, rather than a generic wing thickness. Manufacturing properties and equipment mass scaling are provisional.','',
      'The reference wing is a rectangular extrusion of the CAD midsection. Camber, thickness, aspect ratio, area and mast position are independent geometry inputs. The hull is an elliptical-planform sizing family. Keel and rudder use a 12%-thick elliptic section family; section-shape optimization is not implemented.','',
      'The volume-normalized 3:1:1 bulb sits immediately below the keel tip without overlap; its joint still needs structural detailing. Seam/finish mass is included but its displacement is omitted. Flooding, retained water and trim-dependent wing centroid are not yet part of this mass replay.','',
      '## VSPAERO response surface','',
      f"The saved grid contains {len(cases)} aspect/camber combinations, each with eight incidence points: aspect ratios 2, 4, 6 and 8; camber scales 0.5, 1 and 1.5; incidence −12° through 16°. Camber scale 1 reproduces the extracted reference mean line. The mesh setting is 24; reference mesh sensitivity is documented [separately](wing-analysis-results.md).",'',
      'Interpolation returns lift, induced drag and pitching moment about midchord. It rejects out-of-range or nonfinite requests. Profile drag, stall limits and uncertainty factors remain separate engineering inputs; they are not VSPAERO predictions. Thickness is fixed in the grid, and no aerodynamic thickness sensitivity has been established.','',
      'The additional zero-camber case passes the zero-incidence lift/moment symmetry check. Twelve reversed-chord counterparts support an end-for-end transformation for the opposite tack, with lift and moment signs reflected consistently. These inviscid computations still do not validate rounded-edge separation, viscous behavior or square-sail mode.','',
      '## Execution boundary','',
      '```mermaid','flowchart TD','  CAD[CAD section and parameterized geometry] --> G[Surface and volume metrics]','  G --> M[Native SysML mass and center of gravity]','  CAD --> V[OpenVSP / VSPAERO grid]','  V --> I[Bounded polar interpolation]','  M --> C[Coupled sailing / energy / recovery search]','  I --> C','  H[Native SysML immersed-volume kernel] --> C','  D[Native SysML drive-power model] --> C','```','',
      'Detailed inputs and provenance: [mass replay](analysis/coupled-mass-reference.json), [VSPAERO grid](analysis/wing-polar-grid.json), [SysML model](../models/coupled-sizing.sysml). See the [workflow](coupled-sizing.md) for the remaining acceptance gates.','']
    return '\n'.join(lines)

if __name__=='__main__':(ROOT/'docs/coupled-inputs.md').write_text(publication(),encoding='utf-8')
