"""Publish the current geometry/VSP evidence without implying qualification."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def publication():
    geometry=json.loads((ROOT/'docs/analysis/wing-geometry.json').read_text())
    reports=[json.loads((ROOT/f'docs/analysis/wing-vsp-reference-{n}.json').read_text()) for n in [16,32,64]]
    lines=['# CAD wing and VSPAERO reference analysis','', '<!-- Generated by scripts.publish_wing_analysis; do not edit numerical results here. -->','',
      'The reference wing is an integration and mesh-sensitivity exercise, **not a validated sizing polar**. It uses the CAD midsection in a rectangular free-air wing. Viscous/stall behavior, rounded-edge wake shedding, broadside flow, hull interference and both-tack operation remain unvalidated.','',
      '## Geometry','',f"CAD source: `{geometry['source']}`. Length units: millimetres. CAD axes: X chord, Y span, Z section height.",'',
      f"Material volume of the imported solid: **{geometry['solid_properties']['signed_volume_mm3']/1e6:.6f} litres**. This is not sealed displacement volume.",'','| Span station (mm) | Chord (mm) | Outer area (mm²) | Missing envelope samples |','|---:|---:|---:|---:|']
    for p in geometry['profiles']:
        area='Unavailable' if p['enclosed_area_mm2'] is None else f"{p['enclosed_area_mm2']:.2f}"
        lines.append(f"| {p['span_station_mm']} | {p['chord_mm']:.3f} | {area} | {p['incomplete_samples']} |")
    lines+=['','![Extracted wing sections](figures/wing-sections.png)','','## Reference sweep','',
      f"Tool: {reports[0]['tool']}. Reference area {reports[0]['area_m2']} m²; aspect ratio {reports[0]['aspectRatio']}; mast moment reference at mid-chord. CAD Z is reflected to give positive camber in aerodynamic axes. These dimensions are reference inputs, not frozen design requirements.",'',
      '| Incidence (deg) | CL, mesh 16 | CL, mesh 32 | CL, mesh 64 | CDi, mesh 64 | CMy, mesh 64 |','|---:|---:|---:|---:|---:|---:|']
    for i,alpha in enumerate(reports[0]['results']['Alpha']):
        vals=[r['results']['CLtot'][i] for r in reports]+[reports[-1]['results'][k][i] for k in ['CDi','CMytot']]
        lines.append('| '+str(alpha)+' | '+' | '.join(f'{v:.5f}' for v in vals)+' |')
    delta=max(abs(a-b) for a,b in zip(reports[1]['results']['CLtot'],reports[2]['results']['CLtot']))
    lines+=['',f'Maximum absolute CL change from mesh 32 to 64: **{delta:.5f}**. Mesh sensitivity does not validate the physical model. CDi is induced drag, not total sail drag. No observed stall limit is inferred from this sweep.','',
      'Next gates: geometry/axis verification, reference-solver verification, physically defensible aerodynamic coverage and uncertainty, full-angle hydrostatics, actuator/structure coupling, then feasibility and length optimization. See [coupled sizing](coupled-sizing.md).','']
    return '\n'.join(lines)

if __name__=='__main__':(ROOT/'docs/wing-analysis-results.md').write_text(publication(),encoding='utf-8')
