"""Publish the current static recovery diagnostic and its limits."""
import json
import numpy as np
from .native_design_kernel import ROOT
from .study_open_sizing import validate


def report():
    r=json.loads((ROOT/'docs/analysis/hydrostatics.json').read_text());validate(r['sourceHashes'])
    lines=['# Full-angle static recovery diagnostic','', '<!-- Generated by scripts.publish_hydrostatics from the saved native-kernel analysis. -->','',
      'This diagnostic applies a geometry-based buoyancy model to the saved two-metre sizing design. **It is not a capsize qualification or an optimized design.** The hull/wing geometry is provisional and its material mass has not yet been recalculated.','',
      'The sealed-wing cases have restoring roll moments at the sampled interior angles. Removing wing buoyancy produces a non-restoring roll region near inversion. This makes sealed volume and damage/flooding cases sizing inputs; the old below-bottom CG screen cannot replace them. Pitch-unstable branches are retained and identified rather than silently discarded.','',
      '![Static righting curves](figures/hydrostatics.png)','','## Cases','',
      '| Water density (kg/m³) | Mast trim (deg) | Wing buoyancy | Minimum signed restoring moment, sampled interior (N m) | Pitch-unstable samples |','|---:|---:|---|---:|---:|']
    for c in r['cases']:
        lines.append(f"| {c['density_kg_m3']:.0f} | {c['mast_trim_deg']:.0f} | {c['wing_state'].replace('_',' ')} | {c['minimum_sampled_restoring_Nm']:.2f} | {sum(not p['pitch_stable'] for p in c['points'])} |")
    lines+=['','Signed restoring moment is positive toward upright on either side. The sweep includes both sides from -180 to +180 degrees in 7.5-degree increments. Interior minima exclude upright and exact inversion; they do not establish positive moment between samples or eliminate all other three-dimensional equilibria.','',
      '## Geometry refinement','', '| Wing state | Heel (deg) | Coarse moment (N m) | Refined moment (N m) | Change (N m) |','|---|---:|---:|---:|---:|']
    for p in r['mesh_refinement']:
        lines.append(f"| {p['wing_state'].replace('_',' ')} | {p['heel_deg']:.0f} | {p['coarse_righting_Nm']:.2f} | {p['fine_righting_Nm']:.2f} | {p['change_Nm']:.2f} |")
    lines+=['',f"Hull and ballast tessellation increases from resolution {r['resolution']} to {2*r['resolution']} at these points; the CAD wing section uses 40 chord strips. This is numerical sensitivity evidence, not geometry validation.",'',
      '## Method and assumptions','',
      '[hydrostatics.sysml](../models/hydrostatics.sysml) owns exact planar clipping of each tetrahedron, displaced volume/first moments, and gravity/buoyancy balance. Python constructs geometry and solves immersion and pitch numerically; a small C adapter batches calls to the generated SysML kernel. Independent tests compare clipped shapes with a convex-hull oracle and analytic box stability.','',
      r['scope'],'',
      'The hull has an elliptical planform, rounded bottom and vertical topsides. The wing is a rectangular extrusion of the CAD midsection, trimmed about mid-chord; camber and mast fraction are parameterized. Ballast is a provisional 3:1:1 ellipsoid. Component geometry does not overlap. Dynamic recovery, wave loads, retained water, compartment flooding and revised geometry-derived structural mass remain integration work.','',
      '## Reproduce','',
      'Compile on Windows with `uv run python -m scripts.native_hydrostatics`. Run `python -m scripts.study_hydrostatics` in the Linux/GCC numerical environment, then `uv run python -m scripts.publish_hydrostatics`. Run `python -m pytest tests/test_hydrostatics.py` in that numerical environment.','',
      'The next sizing integration will use these geometry calculations with recalculated mass, actuator loads and candidate-specific aerodynamics. See [coupled sizing](coupled-sizing.md).','']
    return r,'\n'.join(lines)


def publish():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    r,text=report();fig,axes=plt.subplots(1,2,figsize=(11,4))
    for ax,state in zip(axes,['sealed','lost_wing_buoyancy']):
        for c in r['cases']:
            if c['density_kg_m3']!=1000 or c['wing_state']!=state:continue
            p=[p for p in c['points'] if p['heel_deg']>=0]
            ax.plot([x['heel_deg'] for x in p],[x['righting_Nm'] for x in p],label=f"Trim {c['mast_trim_deg']:.0f}°")
            unstable=[x for x in p if not x['pitch_stable']]
            if unstable:ax.scatter([x['heel_deg'] for x in unstable],[x['righting_Nm'] for x in unstable],facecolors='none',edgecolors='black',s=20)
        ax.axhline(0,color='black',lw=.8);ax.set(xlabel='Prescribed heel / degrees',ylabel='Restoring roll moment / N m',title=state.replace('_',' ').capitalize());ax.grid(alpha=.3);ax.legend()
    fig.suptitle('Provisional two-metre geometry, freshwater\nHollow markers: pitch-unstable equilibrium branch; not a dynamic recovery result',fontsize=10)
    fig.tight_layout();fig.savefig(ROOT/'docs/figures/hydrostatics.png',dpi=180);plt.close(fig)
    (ROOT/'docs/hydrostatics.md').write_text(text,encoding='utf-8')

if __name__=='__main__':publish()
