"""Publish saved SciPy candidates as native SysML subjects, never as verdicts."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read_search():
    report = json.loads((ROOT / "docs/analysis/design-search.json").read_text(encoding="utf-8"))
    for name, expected in (report["contract"]["sourceHashes"] | report["driverHashes"]).items():
        actual = hashlib.sha256((ROOT / name).read_bytes().replace(b"\r\n", b"\n")).hexdigest()
        if actual != expected:
            raise ValueError(f"Stale design search: {name}; prepare and rerun the search")
    return report


def result_model(report):
    lines = ["package BlueDogDesignResults {", "    doc /* Generated by scripts/publish_design_search.py from saved search inputs.",
             "     * Numerical outputs are recomputed by SearchAudit; no physical evidence is accepted. */"]
    for name, study in report["studies"].items():
        best = study["best"]
        design = [best["design"][key] for key in report["contract"]["designNames"]]
        sequence = lambda values: "(" + ", ".join(format(v, ".17g") for v in values) + ")"
        lines += [f"    part {name} : BlueDogDesignSearch::SearchResult {{",
                  f'        attribute :>> label = "{name}";',
                  f"        attribute :>> design = {sequence(design)};",
                  "        attribute :>> evidenceAccepted = false;"]
        for index, values in zip(best["scenarioIndices"], best["states"], strict=True):
            lines += [f"        part point{index+1} :> points {{",
                      f"            attribute :>> index = {index+1};",
                      f"            attribute :>> operatingValues = {sequence(values)};", "        }"]
        lines += ["    }", f"    analysis {name}Audit : BlueDogDesignSearch::SearchAudit {{ subject :>> trial = {name}; }}"]
    return "\n".join(lines + ["}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = result_model(read_search())
    path = ROOT / "models/design-search-results.sysml"
    if args.check:
        if path.read_text(encoding="utf-8") != content:
            raise SystemExit("Stale generated design-search-results.sysml")
    else:
        path.write_bytes(content.encode())


if __name__ == "__main__":
    main()
